# Generated by Django 5.1.1 on 2025-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kilishi', '0003_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
